spring:
  batch:
    jdbc:
      initialize-schema: always
      isolation-level-for-create: read_committed
    job:
      enabled: false # 서버 실행 시 배치 자동 실행 여부
      name: testJob # 배치 자동 실행 시 실행할 job 이름
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.Oracle10gDialect
        format_sql: true
        highlight_sql: true
    show-sql: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: test
    password: 1234